# -*-Makefile-*-
#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------
CC            = gcc
CXX           = g++
LD            = $(CXX) $(CCFLAGS) $(CPPFLAGS)
AR            = ar
PICFLAGS      = -fPIC
CPPFLAGS      = $(PICFLAGS) $(GENFLAGS) -std=c++11 -D_REENTRANT
OBJEXT        = .o
OUTPUT_OPTION = -o "$@"
COMPILE.c     = $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE.cc    = $(CXX) $(CCFLAGS) $(CPPFLAGS) -c
LDFLAGS       = -L"."
CCC           = $(CXX)
MAKEFILE      = Makefile.queens_solver
DEPENDENCIES  = .depend.$(MAKEFILE)
BTARGETDIR    = ./
BIN           = $(BTARGETDIR)queens_solver$(EXESUFFIX)$(EXEEXT)
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
EXEEXT        = 
LIBPREFIX     = lib
LIBSUFFIX     = 
GENFLAGS      = -O
LDLIBS        = -ldl $(subst lib,-l,$(sort $(basename $(notdir $(wildcard /usr/lib/librt.so /lib/librt.so))))) -lpthread
OBJS          = driver$(OBJEXT) Queens_Solver$(OBJEXT) devtools/Commands/Queen_Command/Place_Queen_Command$(OBJEXT) devtools/Commands/Queen_Command/Remove_Queen_Command$(OBJEXT) devtools/Factory/Cmd_Factory/Concrete_Expr_Command_Factory$(OBJEXT) devtools/Factory/Main_Factory/Concrete_Factory$(OBJEXT) devtools/Factory/Query_Factory/Concrete_Expr_Query_Factory$(OBJEXT) devtools/Query/Query_Queen/Diagonal_Conflict_Query$(OBJEXT) devtools/Query/Query_Queen/Horizontal_Conflict_Query$(OBJEXT) devtools/Stack/Stack$(OBJEXT)
SOEXT         = .so
SRC           = driver.cpp Queens_Solver.cpp devtools/Commands/Queen_Command/Place_Queen_Command.cpp devtools/Commands/Queen_Command/Remove_Queen_Command.cpp devtools/Factory/Cmd_Factory/Concrete_Expr_Command_Factory.cpp devtools/Factory/Main_Factory/Concrete_Factory.cpp devtools/Factory/Query_Factory/Concrete_Expr_Query_Factory.cpp devtools/Query/Query_Queen/Diagonal_Conflict_Query.cpp devtools/Query/Query_Queen/Horizontal_Conflict_Query.cpp devtools/Stack/Stack.cpp
LINK.cc       = $(LD) $(LDFLAGS)
EXPORTFLAGS   = 
DEPLIBS       = $(foreach lib, , $(foreach libpath, ., $(wildcard $(libpath)/lib$(lib).a)))

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(BIN)

$(BIN): $(OBJS) $(DEPLIBS)
	@$(TESTDIRSTART) "$(BTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(BTARGETDIR)"
	$(LINK.cc) $(OBJS) $(LDLIBS) $(OUTPUT_OPTION)

generated: $(GENERATED_DIRTY)
	@-:

driver$(OBJEXT): driver.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) driver.cpp

Queens_Solver$(OBJEXT): Queens_Solver.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) Queens_Solver.cpp

devtools/Commands/Queen_Command/Place_Queen_Command$(OBJEXT): devtools/Commands/Queen_Command/Place_Queen_Command.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) devtools/Commands/Queen_Command/Place_Queen_Command.cpp

devtools/Commands/Queen_Command/Remove_Queen_Command$(OBJEXT): devtools/Commands/Queen_Command/Remove_Queen_Command.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) devtools/Commands/Queen_Command/Remove_Queen_Command.cpp

devtools/Factory/Cmd_Factory/Concrete_Expr_Command_Factory$(OBJEXT): devtools/Factory/Cmd_Factory/Concrete_Expr_Command_Factory.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) devtools/Factory/Cmd_Factory/Concrete_Expr_Command_Factory.cpp

devtools/Factory/Main_Factory/Concrete_Factory$(OBJEXT): devtools/Factory/Main_Factory/Concrete_Factory.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) devtools/Factory/Main_Factory/Concrete_Factory.cpp

devtools/Factory/Query_Factory/Concrete_Expr_Query_Factory$(OBJEXT): devtools/Factory/Query_Factory/Concrete_Expr_Query_Factory.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) devtools/Factory/Query_Factory/Concrete_Expr_Query_Factory.cpp

devtools/Query/Query_Queen/Diagonal_Conflict_Query$(OBJEXT): devtools/Query/Query_Queen/Diagonal_Conflict_Query.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) devtools/Query/Query_Queen/Diagonal_Conflict_Query.cpp

devtools/Query/Query_Queen/Horizontal_Conflict_Query$(OBJEXT): devtools/Query/Query_Queen/Horizontal_Conflict_Query.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) devtools/Query/Query_Queen/Horizontal_Conflict_Query.cpp

devtools/Stack/Stack$(OBJEXT): devtools/Stack/Stack.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) devtools/Stack/Stack.cpp

clean:
	-$(RM) $(OBJS)

realclean: clean
	-$(RM) $(BIN)

check-syntax:
	$(COMPILE.cc) $(EXPORTFLAGS) -Wall -Wextra -pedantic -fsyntax-only $(CHK_SOURCES)

#----------------------------------------------------------------------------
#       Dependencies
#----------------------------------------------------------------------------


depend:
	-$(MPC_ROOT)/depgen.pl  $(CFLAGS) $(CCFLAGS) $(CPPFLAGS) -f $(DEPENDENCIES) $(SRC) 2> $(NUL)

-include $(DEPENDENCIES)
