# -*-Makefile-*-
#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# ../MPC/mwc.pl -type make
#
#----------------------------------------------------------------------------


all: queens_solver

depend: queens_solver-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@"$(MAKE)" -f Makefile.queens_solver $(@)

.PHONY: queens_solver
queens_solver:
	@"$(MAKE)" -f Makefile.queens_solver all

.PHONY: queens_solver-depend
queens_solver-depend:
	@"$(MAKE)" -f Makefile.queens_solver depend

project_name_list:
	@echo queens_solver
